import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ChevronDown, ChevronLeft, ChevronRight, Menu, Search, X } from 'lucide-react';
import './styles.css';

const properties = [
  { title: 'The Meridian Residence', type: 'For Sale', category: 'Residential', location: 'Ikoyi, Lagos', price: '₦485M', beds: 4, baths: 5, image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85' },
  { title: 'Palm Court Apartments', type: 'For Rent', category: 'Residential', location: 'Lekki Phase 1, Lagos', price: '₦18M / yr', beds: 3, baths: 4, image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=85' },
  { title: 'Cedar Crest Land', type: 'Land', category: 'Land', location: 'Ajah, Lagos', price: '₦95M', beds: null, baths: null, image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=85' },
  { title: 'Eko Atlantic View', type: 'Featured', category: 'Commercial', location: 'Eko Atlantic, Lagos', price: '₦1.2B', beds: 5, baths: 6, image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85' }
];
const services = ['Property Sales', 'Property Letting & Rentals', 'Land Sales', 'Property Management', 'Real Estate Development', 'Property Investment', 'Valuation', 'Real Estate Consultancy', 'Facility Management'];
const locations = ['Ikoyi', 'Victoria Island', 'Lekki', 'Banana Island', 'Ikeja', 'Ajah', 'Eko Atlantic', 'Oniru', 'Omole', 'Maitama', 'Asokoro', 'Wuse', 'Gwarinpa', 'Guzape'];
function App() {
 const [menuOpen,setMenuOpen]=useState(false),[filter,setFilter]=useState('All'),[activeProperty,setActiveProperty]=useState(null),[showSearch,setShowSearch]=useState(false),[locationIndex,setLocationIndex]=useState(0);
 const filtered=useMemo(()=>filter==='All'?properties:properties.filter(p=>p.category===filter),[filter]);
 const scrollTo=id=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 const whatsapp=p=>`https://wa.me/2347031280458?text=${encodeURIComponent(`Hello Aremu Olusoji & Associates, I am interested in ${p.title} in ${p.location}. Please share availability and details.`)}`;
 return <div className="site-shell">
  <header className="nav"><button className="brand" onClick={()=>scrollTo('top')} aria-label="Aremu Olusoji & Associates home"><img src="/logo.svg" alt="Aremu Olusoji & Associates"/></button><nav className={menuOpen?'nav-links open':'nav-links'}>{['Properties','Services','Locations','About','Insights'].map(item=><button key={item} onClick={()=>scrollTo(item.toLowerCase())}>{item}</button>)}<button className="nav-cta" onClick={()=>scrollTo('contact')}>Speak with an advisor <ArrowUpRight size={15}/></button></nav><button className="mobile-menu" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle menu">{menuOpen?<X/>:<Menu/>}</button></header>
  <main id="top">
   <section className="hero"><div className="hero-media"/><div className="hero-grain"/><div className="hero-copy reveal"><p className="eyebrow">Aremu Olusoji &amp; Associates · Lagos · Nigeria</p><h1>Property,<br/><em>elevated.</em></h1><p className="hero-sub">Exceptional homes. Strategic investments. Professional real-estate solutions.</p><div className="hero-actions"><button className="gold-btn" onClick={()=>scrollTo('properties')}>Explore properties <ArrowUpRight size={17}/></button><button className="text-btn" onClick={()=>scrollTo('contact')}>Speak with an advisor <span>↗</span></button></div></div><div className="hero-footer"><span>YOUR VISION. OUR PRIORITY.</span><span>Scroll to discover ↓</span></div></section>
   <section className="search-panel" id="search"><div className="search-intro"><span>01</span><h2>Find your next<br/><em>address.</em></h2></div><div className="search-fields">{['Purpose','Location','Property type','Price range'].map((label,i)=><button className="field" key={label} onClick={()=>setShowSearch(true)}><small>{label}</small><strong>{['Buy / Rent','Lagos, Nigeria','Any property','Any budget'][i]}</strong><ChevronDown size={16}/></button>)}<button className="search-submit" onClick={()=>setShowSearch(true)}><Search size={19}/><span>Search</span></button></div></section>
   <section className="section properties" id="properties"><div className="section-head"><div><p className="eyebrow dark">Curated opportunities</p><h2>Featured <em>properties.</em></h2></div><button className="outline-btn" onClick={()=>setShowSearch(true)}>View all properties <ArrowUpRight size={16}/></button></div><div className="filters">{['All','Residential','Land','Commercial'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="property-grid">{filtered.map((p,i)=><article className="property-card" key={p.title} onClick={()=>setActiveProperty(p)}><div className="property-image"><img src={p.image} alt="" loading={i>1?'lazy':'eager'}/><span>{p.type}</span><button aria-label="Open property"><ArrowUpRight size={17}/></button></div><div className="property-meta"><div><h3>{p.title}</h3><p>{p.location}</p></div><strong>{p.price}</strong></div><div className="property-stats">{p.beds?<><span>{p.beds} beds</span><i/><span>{p.baths} baths</span><i/></>:<><span>Development land</span><i/></>}<span>{p.category}</span></div></article>)}</div></section>
   <section className="statement"><div className="statement-number">02</div><p className="eyebrow">Our approach</p><h2>More than property.<br/><em>Peace of mind.</em></h2><p className="statement-copy">We combine local market understanding, careful property selection and professional guidance to make every real-estate decision clearer — from first enquiry to long-term ownership.</p><div className="principles">{['Professional guidance','Curated opportunities','End-to-end service','Client-centred approach'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section>
   <section className="services section" id="services"><div className="section-head"><div><p className="eyebrow dark">What we do</p><h2>One partner.<br/><em>Every property need.</em></h2></div><p className="section-note">From acquisition and leasing to management, valuation and development, our services are designed around the complete property journey.</p></div><div className="service-list">{services.map((service,i)=><button key={service} onClick={()=>scrollTo('contact')}><span>0{i+1}</span><strong>{service}</strong><ArrowUpRight size={20}/></button>)}</div></section>
   <section className="locations section" id="locations"><div className="section-head"><div><p className="eyebrow dark">Explore by location</p><h2>Places with<br/><em>possibility.</em></h2></div><div className="carousel-controls"><button onClick={()=>setLocationIndex(Math.max(0,locationIndex-1))}><ChevronLeft/></button><button onClick={()=>setLocationIndex(Math.min(locations.length-4,locationIndex+1))}><ChevronRight/></button></div></div><div className="location-track" style={{transform:`translateX(-${locationIndex*25}%)`}}>{locations.map((loc,i)=><div className="location-card" key={loc}><div style={{backgroundImage:`url(${['https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?auto=format&fit=crop&w=900&q=80'][i%4]}`}}/><span>{String(i+1).padStart(2,'0')}</span><h3>{loc}</h3><p>Nigeria</p></div>)}</div></section>
   <section className="split-feature" id="about"><div className="split-image"/><div className="split-copy"><p className="eyebrow dark">About Aremu Olusoji &amp; Associates</p><h2>A more thoughtful approach to <em>real estate.</em></h2><p>Aremu Olusoji &amp; Associates is a full-service real estate firm dedicated to connecting individuals, families, businesses and investors with exceptional property opportunities across Nigeria.</p><p>From premium residential properties and strategically located land to property management, development, valuation and investment advisory, we provide a comprehensive approach to real estate.</p><button className="outline-btn" onClick={()=>scrollTo('contact')}>Start a conversation <ArrowUpRight size={16}/></button></div></section>
   <section className="investment"><div><p className="eyebrow">For investors &amp; developers</p><h2>Build beyond <em>today.</em></h2><p>Explore acquisition, development and investment opportunities with a partner focused on the details behind the asset.</p><button className="gold-btn" onClick={()=>scrollTo('contact')}>Discuss an opportunity <ArrowUpRight size={17}/></button></div><div className="investment-orbit"><span>PROPERTY</span><strong>VALUE</strong><small>LONG-TERM</small></div></section>
   <section className="insights section" id="insights"><div className="section-head"><div><p className="eyebrow dark">Insights</p><h2>Ideas worth<br/><em>knowing.</em></h2></div><button className="outline-btn" onClick={()=>scrollTo('contact')}>Explore insights <ArrowUpRight size={16}/></button></div><div className="insight-grid"><article><div className="insight-image a"/><p>REAL ESTATE</p><h3>What to consider before acquiring property in Lagos</h3><button>Read insight ↗</button></article><article><div className="insight-image b"/><p>INVESTMENT</p><h3>Building a property portfolio with a long-term view</h3><button>Read insight ↗</button></article><article><div className="insight-image c"/><p>GUIDE</p><h3>A practical guide to professional property management</h3><button>Read insight ↗</button></article></div></section>
   <section className="contact" id="contact"><div className="contact-copy"><p className="eyebrow">Let's start the conversation</p><h2>Your next property decision starts <em>here.</em></h2><p>Tell us what you are looking for and our team will help you identify the right next step.</p><div className="contact-details"><a href="tel:07031280458">0703 128 0458</a><a href="tel:08023209689">0802 320 9689</a><a href="mailto:olusoji.aremu1@gmail.com">olusoji.aremu1@gmail.com</a><span>Gbemishola House, opposite Omole Social Club, Lagos, Nigeria</span></div></div><form className="contact-form" onSubmit={e=>{e.preventDefault();alert('Thank you. Your enquiry has been prepared for the Aremu Olusoji & Associates team.')}}><label>Full name<input required placeholder="Your name"/></label><label>Email address<input required type="email" placeholder="you@example.com"/></label><label>Phone number<input placeholder="0703..."/></label><label>How can we help?<textarea rows="4" placeholder="Tell us what you are looking for..."/></label><button className="gold-btn" type="submit">Send enquiry <ArrowUpRight size={17}/></button></form></section>
  </main>
  <footer><div className="footer-brand"><img src="/logo.svg" alt="Aremu Olusoji &amp; Associates"/><p>Your Vision. Our Priority.</p></div><div><span>CONTACT</span><a href="tel:07031280458">0703 128 0458</a><a href="mailto:olusoji.aremu1@gmail.com">olusoji.aremu1@gmail.com</a></div><div><span>CONNECT</span><a href="https://wa.me/2347031280458" target="_blank" rel="noreferrer">WhatsApp</a><a href="https://web.facebook.com/oiusoji.aremu1" target="_blank" rel="noreferrer">Facebook</a></div><div><span>NAVIGATE</span><button onClick={()=>scrollTo('properties')}>Properties</button><button onClick={()=>scrollTo('services')}>Services</button><button onClick={()=>scrollTo('contact')}>Contact</button></div><div className="copyright">© {new Date().getFullYear()} Aremu Olusoji &amp; Associates. All rights reserved.</div></footer>
  {showSearch&&<div className="modal-backdrop" onClick={()=>setShowSearch(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowSearch(false)}><X/></button><p className="eyebrow dark">Property search</p><h2>Tell us what you are <em>looking for.</em></h2><p>Our full property inventory can be connected to this interface as listings become available.</p><button className="gold-btn" onClick={()=>{setShowSearch(false);scrollTo('contact')}}>Speak with an advisor <ArrowUpRight size={17}/></button></div></div>}
  {activeProperty&&<div className="modal-backdrop" onClick={()=>setActiveProperty(null)}><div className="property-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setActiveProperty(null)}><X/></button><img src={activeProperty.image} alt=""/><div className="property-modal-copy"><p className="eyebrow dark">{activeProperty.type} · {activeProperty.category}</p><h2>{activeProperty.title}</h2><p>{activeProperty.location}</p><strong className="modal-price">{activeProperty.price}</strong><div className="modal-actions"><a className="gold-btn" href={whatsapp(activeProperty)} target="_blank" rel="noreferrer">WhatsApp enquiry <ArrowUpRight size={17}/></a><button className="outline-btn" onClick={()=>{setActiveProperty(null);scrollTo('contact')}}>Schedule a viewing</button></div></div></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
